const STORE='cfsWebsiteData',AUTH='cfsAdminSession';
const defaults={contact:{phone:'0435 744 000',phoneLink:'+61435744000',email:'info@crishfacilityservices.com.au',address:'17 Coronation St, Sunshine North, VIC 3020',whatsapp:'94766280198'},slides:[
{kicker:'Commercial cleaning · Melbourne',title1:'Immaculate spaces.',title2:'Ready for business.',copy:'Considered commercial cleaning that protects your presentation, your people and every first impression.',image:'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=2200&q=90',link:'cleaning-services.html',cta:'Explore commercial cleaning'},
{kicker:'Office & workplace care',title1:'A better workplace.',title2:'Every single day.',copy:'Reliable scheduled cleaning for offices, shared spaces and high-touch environments—delivered around your operations.',image:'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=2200&q=90',link:'cleaning-services.html',cta:'View workplace services'},
{kicker:'Glass & window cleaning',title1:'Clarity you can see.',title2:'Standards you can trust.',copy:'Specialist glass care for brighter interiors, polished arrivals and a consistently professional exterior.',image:'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=2200&q=90',link:'cleaning-services.html',cta:'Discover specialist cleaning'},
{kicker:'Pressure & exterior cleaning',title1:'Restore every surface.',title2:'Elevate every arrival.',copy:'Powerful exterior cleaning for paths, façades, loading areas and car parks, managed with precision and care.',image:'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?auto=format&fit=crop&w=2200&q=90',link:'cleaning-services.html',cta:'Explore exterior care'},
{kicker:'Commercial grounds care',title1:'Beautiful grounds.',title2:'All year round.',copy:'Commercial mowing, garden maintenance and seasonal grounds programs tailored to Melbourne properties.',image:'https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=2200&q=90',link:'gardening-services.html',cta:'Explore gardening services'}],reviews:[
{name:'Olivia Hart',role:'Operations Director',category:'Corporate',rating:5,quote:'The difference was visible from the very first service. The team is professional, proactive and genuinely cares about our workplace.'},
{name:'Marcus Lee',role:'General Manager',category:'Premium retail',rating:5,quote:'Our showroom has never looked better. Crish Facility Services understands that immaculate presentation is part of our customer experience.'},
{name:'Amelia Ross',role:'Facilities Manager',category:'Property',rating:5,quote:'Communication is effortless, standards are consistent and every request is handled quickly. Exactly what a facility partnership should feel like.'},
{name:'Daniel Cole',role:'Practice Director',category:'Allied health',rating:5,quote:'They designed a schedule around our operating hours and made the entire transition completely seamless for staff and patients.'},
{name:'Sophie Bennett',role:'Centre Manager',category:'Education',rating:5,quote:'Crish Facility Services feels less like a supplier and more like a trusted part of our team. They notice things before we even need to ask.'},
{name:'James Wilson',role:'Group Owner',category:'Hospitality',rating:5,quote:'Reliable, discreet and incredibly thorough. It is the confidence we need from a partner working behind the scenes of our guest experience.'}]};
const clone=x=>JSON.parse(JSON.stringify(x));let data=(()=>{try{return {...clone(defaults),...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return clone(defaults)}})();
const login=document.querySelector('[data-login-screen]'),shell=document.querySelector('[data-admin-shell]');
function enter(){login.hidden=true;shell.hidden=false;renderSlides();renderReviews();fillContact()}
if(sessionStorage.getItem(AUTH)==='yes')enter();
document.querySelector('[data-login-form]').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('username')==='admin'&&f.get('password')==='CFS2026'){sessionStorage.setItem(AUTH,'yes');enter()}else document.querySelector('[data-login-error]').textContent='Incorrect username or password. Please try again.'});
document.querySelector('[data-logout]').addEventListener('click',()=>{sessionStorage.removeItem(AUTH);location.reload()});
const titles={overview:'Dashboard overview',carousel:'Hero carousel manager',reviews:'Client reviews manager',contact:'Contact details',settings:'Site settings'};
function openPanel(name){document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));document.querySelectorAll('[data-panel-target]').forEach(x=>x.classList.toggle('active',x.dataset.panelTarget===name));document.querySelector('[data-page-title]').textContent=titles[name];document.querySelector('[data-sidebar]').classList.remove('open');scrollTo(0,0)}
document.querySelectorAll('[data-panel-target]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panelTarget)));document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.jump)));document.querySelector('[data-sidebar-toggle]').addEventListener('click',()=>document.querySelector('[data-sidebar]').classList.toggle('open'));
const save=()=>localStorage.setItem(STORE,JSON.stringify(data));const toast=msg=>{const t=document.querySelector('[data-admin-toast]');t.textContent=msg||'Changes saved and published locally.';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)};
const list=document.querySelector('[data-slide-list]'),editor=document.querySelector('[data-slide-editor]');
function renderSlides(){list.innerHTML='';data.slides.forEach((s,i)=>{const card=document.createElement('article');card.className='slide-admin-card';const img=document.createElement('img');img.src=s.image;img.alt='';const info=document.createElement('div');const small=document.createElement('small');small.textContent=`Slide ${String(i+1).padStart(2,'0')} · ${s.kicker}`;const b=document.createElement('b');b.textContent=`${s.title1} ${s.title2}`;const p=document.createElement('p');p.textContent=s.copy;info.append(small,b,p);const actions=document.createElement('div');actions.className='slide-actions';const edit=document.createElement('button');edit.textContent='Edit';edit.addEventListener('click',()=>editSlide(i));const del=document.createElement('button');del.textContent='Delete';del.className='delete';del.addEventListener('click',()=>{if(data.slides.length===1)return alert('At least one slide is required.');if(confirm('Delete this carousel slide?')){data.slides.splice(i,1);save();renderSlides();toast('Slide removed from the website.')}});actions.append(edit,del);card.append(img,info,actions);list.append(card)});document.querySelectorAll('[data-slide-count]').forEach(x=>x.textContent=data.slides.length);document.querySelector('[data-stat-slides]').textContent=String(data.slides.length).padStart(2,'0')}
function editSlide(i){const s=data.slides[i];editor.hidden=false;editor.elements.index.value=i;['kicker','title1','title2','copy','image','link','cta'].forEach(k=>editor.elements[k].value=s[k]);document.querySelector('[data-editor-title]').textContent='Edit service slide';editor.scrollIntoView({behavior:'smooth',block:'start'})}
document.querySelector('[data-add-slide]').addEventListener('click',()=>{editor.reset();editor.hidden=false;editor.elements.index.value='new';document.querySelector('[data-editor-title]').textContent='Add new service slide';editor.scrollIntoView({behavior:'smooth',block:'start'})});document.querySelectorAll('[data-close-editor]').forEach(x=>x.addEventListener('click',()=>editor.hidden=true));
editor.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(editor),s={};['kicker','title1','title2','copy','image','link','cta'].forEach(k=>s[k]=f.get(k).trim());const i=f.get('index');if(i==='new')data.slides.push(s);else data.slides[Number(i)]=s;save();renderSlides();editor.hidden=true;toast()});
const reviewList=document.querySelector('[data-review-list]'),reviewEditor=document.querySelector('[data-review-editor]');
const initials=name=>name.trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()||'').join('');
function renderReviews(){reviewList.innerHTML='';data.reviews.forEach((r,i)=>{const card=document.createElement('article');card.className='review-admin-card';const avatar=document.createElement('span');avatar.className='review-admin-avatar';avatar.textContent=initials(r.name);const content=document.createElement('div');const meta=document.createElement('small');meta.textContent=`${r.category} · ${'★'.repeat(Number(r.rating))}`;const name=document.createElement('b');name.textContent=r.name;const role=document.createElement('em');role.textContent=r.role;const quote=document.createElement('p');quote.textContent=`“${r.quote}”`;content.append(meta,name,role,quote);const actions=document.createElement('div');actions.className='slide-actions';const edit=document.createElement('button');edit.textContent='Edit';edit.addEventListener('click',()=>editReview(i));const del=document.createElement('button');del.textContent='Delete';del.className='delete';del.addEventListener('click',()=>{if(confirm('Delete this client review?')){data.reviews.splice(i,1);save();renderReviews();toast('Client review removed from the website.')}});actions.append(edit,del);card.append(avatar,content,actions);reviewList.append(card)});document.querySelectorAll('[data-review-count]').forEach(x=>x.textContent=data.reviews.length);document.querySelector('[data-stat-reviews]').textContent=String(data.reviews.length).padStart(2,'0')}
function editReview(i){const r=data.reviews[i];reviewEditor.hidden=false;reviewEditor.elements.index.value=i;['name','role','category','quote','rating'].forEach(k=>reviewEditor.elements[k].value=r[k]);document.querySelector('[data-review-editor-title]').textContent='Edit client review';reviewEditor.scrollIntoView({behavior:'smooth',block:'start'})}
document.querySelector('[data-add-review]').addEventListener('click',()=>{reviewEditor.reset();reviewEditor.hidden=false;reviewEditor.elements.index.value='new';document.querySelector('[data-review-editor-title]').textContent='Add new client review';reviewEditor.scrollIntoView({behavior:'smooth',block:'start'})});document.querySelectorAll('[data-close-review-editor]').forEach(x=>x.addEventListener('click',()=>reviewEditor.hidden=true));
reviewEditor.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(reviewEditor),r={name:f.get('name').trim(),role:f.get('role').trim(),category:f.get('category').trim(),quote:f.get('quote').trim(),rating:Number(f.get('rating'))};const i=f.get('index');if(i==='new')data.reviews.push(r);else data.reviews[Number(i)]=r;save();renderReviews();reviewEditor.hidden=true;toast('Client review saved and published locally.')});
const contactForm=document.querySelector('[data-contact-form]');function fillContact(){Object.entries(data.contact).forEach(([k,v])=>{if(contactForm.elements[k])contactForm.elements[k].value=v})}contactForm.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);Object.keys(defaults.contact).forEach(k=>data.contact[k]=f.get(k).trim());save();document.querySelector('[data-contact-status]').textContent='Saved and published locally ✓';toast()});
document.querySelector('[data-reset-site]').addEventListener('click',()=>{if(confirm('Restore all carousel, reviews and contact content to the original defaults?')){data=clone(defaults);save();renderSlides();renderReviews();fillContact();toast('Original website content restored.')}});
