const STORE='cfsWebsiteData',AUTH='cfsAdminSession';
const defaults={contact:{phone:'0435 744 000',phoneLink:'+61435744000',email:'info@crishfacilityservices.com.au',address:'17 Coronation St, Sunshine North, VIC 3020',whatsapp:'94766280198'},slides:[
{kicker:'Commercial cleaning · Melbourne',title1:'Immaculate spaces.',title2:'Ready for business.',copy:'Considered commercial cleaning that protects your presentation, your people and every first impression.',image:'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=2200&q=90',link:'cleaning-services.html',cta:'Explore commercial cleaning'},
{kicker:'Office & workplace care',title1:'A better workplace.',title2:'Every single day.',copy:'Reliable scheduled cleaning for offices, shared spaces and high-touch environments—delivered around your operations.',image:'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=2200&q=90',link:'cleaning-services.html',cta:'View workplace services'},
{kicker:'Glass & window cleaning',title1:'Clarity you can see.',title2:'Standards you can trust.',copy:'Specialist glass care for brighter interiors, polished arrivals and a consistently professional exterior.',image:'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=2200&q=90',link:'cleaning-services.html',cta:'Discover specialist cleaning'},
{kicker:'Pressure & exterior cleaning',title1:'Restore every surface.',title2:'Elevate every arrival.',copy:'Powerful exterior cleaning for paths, façades, loading areas and car parks, managed with precision and care.',image:'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?auto=format&fit=crop&w=2200&q=90',link:'cleaning-services.html',cta:'Explore exterior care'},
{kicker:'Commercial grounds care',title1:'Beautiful grounds.',title2:'All year round.',copy:'Commercial mowing, garden maintenance and seasonal grounds programs tailored to Melbourne properties.',image:'https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=2200&q=90',link:'gardening-services.html',cta:'Explore gardening services'}],reviews:[
{name:'Olivia Hart',role:'Operations Director',category:'Corporate',rating:5,photo:'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=240&h=240&q=80',quote:'The difference was visible from the very first service. The team is professional, proactive and genuinely cares about our workplace.'},
{name:'Marcus Lee',role:'General Manager',category:'Premium retail',rating:5,photo:'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=240&h=240&q=80',quote:'Our showroom has never looked better. Crish Facility Services understands that immaculate presentation is part of our customer experience.'},
{name:'Amelia Ross',role:'Facilities Manager',category:'Property',rating:5,photo:'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=240&h=240&q=80',quote:'Communication is effortless, standards are consistent and every request is handled quickly. Exactly what a facility partnership should feel like.'},
{name:'Daniel Cole',role:'Practice Director',category:'Allied health',rating:5,photo:'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=240&h=240&q=80',quote:'They designed a schedule around our operating hours and made the entire transition completely seamless for staff and patients.'},
{name:'Sophie Bennett',role:'Centre Manager',category:'Education',rating:5,photo:'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=240&h=240&q=80',quote:'Crish Facility Services feels less like a supplier and more like a trusted part of our team. They notice things before we even need to ask.'},
{name:'James Wilson',role:'Group Owner',category:'Hospitality',rating:5,photo:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=240&h=240&q=80',quote:'Reliable, discreet and incredibly thorough. It is the confidence we need from a partner working behind the scenes of our guest experience.'},
{name:'Ryan Patel',role:'Site Operations Lead',category:'Warehouse',rating:5,photo:'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=240&h=240&q=80',quote:'They work around our loading schedules without disruption. Floors, amenities and offices stay presentation-ready every single day.'},
{name:'Nina Alvarez',role:'Building Manager',category:'Strata',rating:5,photo:'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=240&h=240&q=80',quote:'Common areas finally feel consistently cared for. Residents notice the difference, and our building manager meetings are much simpler.'},
{name:'Chris Nguyen',role:'Clinic Administrator',category:'Medical',rating:5,photo:'https://images.unsplash.com/photo-1556157382-97eda2d62296?auto=format&fit=crop&w=240&h=240&q=80',quote:'Hygiene standards are exacting, communication is clear, and the team respects the pace of a busy clinical environment.'}],services:[
{name:'Commercial Cleaning',meta:'Core service',description:'Scheduled cleaning programs for offices and commercial properties.',image:'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80',active:true},{name:'Window Cleaning',meta:'Specialist service',description:'Professional glass care for polished interiors and exteriors.',image:'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=900&q=80',active:true},{name:'Pressure Cleaning',meta:'Exterior care',description:'High-pressure surface cleaning for paths, façades and car parks.',image:'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?auto=format&fit=crop&w=900&q=80',active:true},{name:'Commercial Gardening',meta:'Grounds care',description:'Mowing, garden maintenance and seasonal commercial programs.',image:'https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=900&q=80',active:true}],areas:[
{name:'Dandenong',meta:'South-east Melbourne',description:'Commercial cleaning and grounds care.',active:true},{name:'Altona',meta:'Western Melbourne',description:'Commercial cleaning and grounds care.',active:true},{name:'Richmond',meta:'Inner-east Melbourne',description:'Commercial cleaning and grounds care.',active:true},{name:'Sunshine',meta:'Western Melbourne',description:'Commercial cleaning and grounds care.',active:true},{name:'Port Melbourne',meta:'Bayside precinct',description:'Commercial cleaning and grounds care.',active:true},{name:'Fitzroy',meta:'Inner-north Melbourne',description:'Commercial cleaning and grounds care.',active:true},{name:'Collingwood',meta:'Inner-east Melbourne',description:'Commercial cleaning and grounds care.',active:true},{name:'Hallam',meta:'South-east Melbourne',description:'Commercial cleaning and grounds care.',active:true},{name:'Williamstown',meta:'Inner-west Melbourne',description:'Commercial cleaning and grounds care.',active:true},{name:'Yarraville',meta:'Inner-west Melbourne',description:'Commercial cleaning and grounds care.',active:true}],enquiries:[
{id:'CFS-1048',name:'Sarah Mitchell',company:'Apex Business Centre',service:'Commercial Cleaning',location:'Richmond',date:'12 Aug 2026',status:'New',email:'sarah@apex.example',phone:'0412 345 678'},{id:'CFS-1047',name:'Michael Tan',company:'Westgate Logistics',service:'Warehouse Cleaning',location:'Altona',date:'11 Aug 2026',status:'Contacted',email:'michael@westgate.example',phone:'0423 458 901'},{id:'CFS-1046',name:'Emma Wilson',company:'Harbour Health',service:'Window Cleaning',location:'Port Melbourne',date:'10 Aug 2026',status:'Quoted',email:'emma@harbour.example',phone:'0431 880 220'},{id:'CFS-1045',name:'David Chen',company:'North & Co.',service:'Gardening Services',location:'Fitzroy',date:'08 Aug 2026',status:'Won',email:'david@northco.example',phone:'0402 667 314'}],applications:[
{id:'APP-031',name:'Kevin Perera',role:'Commercial Cleaner',date:'12 Aug 2026',documents:'5 of 7',status:'Pending',email:'kevin@example.com'},{id:'APP-030',name:'Lisa Fernando',role:'Gardening Team Member',date:'10 Aug 2026',documents:'7 of 7',status:'Approved',email:'lisa@example.com'},{id:'APP-029',name:'Daniel Silva',role:'Cleaning Contractor',date:'09 Aug 2026',documents:'4 of 7',status:'Needs documents',email:'daniel@example.com'}],media:[
{name:'CFS company logo',src:'assets/crishfacility-logo.jpg',type:'Brand asset'},{name:'Evening cleaning hero',src:'assets/footer-cleaning-city.png',type:'Hero image'},{name:'Commercial workplace',src:'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=900&q=80',type:'Service image'},{name:'Commercial grounds',src:'https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=900&q=80',type:'Service image'}]};
const clone=x=>JSON.parse(JSON.stringify(x));let data=(()=>{try{return {...clone(defaults),...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return clone(defaults)}})();
(()=>{const byName=Object.fromEntries((data.reviews||[]).map(r=>[r.name,r]));const merged=defaults.reviews.map(d=>{const existing=byName[d.name];return existing?{...d,...existing,photo:existing.photo||d.photo}:{...d}});const extras=(data.reviews||[]).filter(r=>!defaults.reviews.some(d=>d.name===r.name));data.reviews=[...merged,...extras];try{localStorage.setItem(STORE,JSON.stringify(data))}catch{}})();
const login=document.querySelector('[data-login-screen]'),shell=document.querySelector('[data-admin-shell]');
function enter(){login.hidden=true;shell.hidden=false;renderSlides();renderReviews();renderCatalog();renderEnquiries();renderApplications();renderMedia();fillContact()}
if(sessionStorage.getItem(AUTH)==='yes')enter();
document.querySelector('[data-login-form]').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('username')==='admin'&&f.get('password')==='CFS2026'){sessionStorage.setItem(AUTH,'yes');enter()}else document.querySelector('[data-login-error]').textContent='Incorrect username or password. Please try again.'});
document.querySelector('[data-logout]').addEventListener('click',()=>{sessionStorage.removeItem(AUTH);location.reload()});
const titles={overview:'Dashboard overview',carousel:'Hero carousel manager',reviews:'Client reviews manager',catalog:'Services and areas',enquiries:'Quote enquiries',applications:'Contractor applications',media:'Media library',contact:'Contact details',settings:'Site settings'};
function openPanel(name){document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));document.querySelectorAll('[data-panel-target]').forEach(x=>x.classList.toggle('active',x.dataset.panelTarget===name));document.querySelector('[data-page-title]').textContent=titles[name];document.querySelector('[data-sidebar]').classList.remove('open');scrollTo(0,0)}
document.querySelectorAll('[data-panel-target]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panelTarget)));document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.jump)));document.querySelector('[data-sidebar-toggle]').addEventListener('click',()=>document.querySelector('[data-sidebar]').classList.toggle('open'));
const save=()=>localStorage.setItem(STORE,JSON.stringify(data));const toast=msg=>{const t=document.querySelector('[data-admin-toast]');t.textContent=msg||'Changes saved and published locally.';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)};
const list=document.querySelector('[data-slide-list]'),editor=document.querySelector('[data-slide-editor]');
function renderSlides(){list.innerHTML='';data.slides.forEach((s,i)=>{const card=document.createElement('article');card.className='slide-admin-card';const img=document.createElement('img');img.src=s.image;img.alt='';const info=document.createElement('div');const small=document.createElement('small');small.textContent=`Slide ${String(i+1).padStart(2,'0')} · ${s.kicker}`;const b=document.createElement('b');b.textContent=`${s.title1} ${s.title2}`;const p=document.createElement('p');p.textContent=s.copy;info.append(small,b,p);const actions=document.createElement('div');actions.className='slide-actions';const edit=document.createElement('button');edit.textContent='Edit';edit.addEventListener('click',()=>editSlide(i));const del=document.createElement('button');del.textContent='Delete';del.className='delete';del.addEventListener('click',()=>{if(data.slides.length===1)return alert('At least one slide is required.');if(confirm('Delete this carousel slide?')){data.slides.splice(i,1);save();renderSlides();toast('Slide removed from the website.')}});actions.append(edit,del);card.append(img,info,actions);list.append(card)});document.querySelectorAll('[data-slide-count]').forEach(x=>x.textContent=data.slides.length);document.querySelector('[data-stat-slides]').textContent=String(data.slides.length).padStart(2,'0')}
function editSlide(i){const s=data.slides[i];editor.hidden=false;editor.elements.index.value=i;['kicker','title1','title2','copy','image','link','cta'].forEach(k=>editor.elements[k].value=s[k]);document.querySelector('[data-editor-title]').textContent='Edit service slide';editor.scrollIntoView({behavior:'smooth',block:'start'})}
document.querySelector('[data-add-slide]').addEventListener('click',()=>{editor.reset();editor.hidden=false;editor.elements.index.value='new';document.querySelector('[data-editor-title]').textContent='Add new service slide';editor.scrollIntoView({behavior:'smooth',block:'start'})});document.querySelectorAll('[data-close-editor]').forEach(x=>x.addEventListener('click',()=>editor.hidden=true));
editor.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(editor),s={};['kicker','title1','title2','copy','image','link','cta'].forEach(k=>s[k]=f.get(k).trim());const i=f.get('index');if(i==='new')data.slides.push(s);else data.slides[Number(i)]=s;save();renderSlides();editor.hidden=true;toast()});
const reviewList=document.querySelector('[data-review-list]'),reviewEditor=document.querySelector('[data-review-editor]');
const initials=name=>String(name||'').trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()||'').join('');
const reviewPhotoPreview=document.querySelector('[data-review-photo-preview]');
const setReviewPhotoPreview=src=>{
  if(!reviewPhotoPreview)return;
  if(src){reviewPhotoPreview.innerHTML='';const img=document.createElement('img');img.src=src;img.alt='Client photo preview';reviewPhotoPreview.append(img);reviewPhotoPreview.classList.add('has-photo')}
  else{reviewPhotoPreview.innerHTML='<span>No photo</span>';reviewPhotoPreview.classList.remove('has-photo')}
};
function renderReviews(){reviewList.innerHTML='';data.reviews.forEach((r,i)=>{const card=document.createElement('article');card.className='review-admin-card';const avatar=document.createElement('span');avatar.className='review-admin-avatar';if(r.photo){const img=document.createElement('img');img.src=r.photo;img.alt=r.name;avatar.append(img);avatar.classList.add('has-photo')}else avatar.textContent=initials(r.name);const content=document.createElement('div');const meta=document.createElement('small');meta.textContent=`${r.category} · ${'★'.repeat(Number(r.rating))}`;const name=document.createElement('b');name.textContent=r.name;const role=document.createElement('em');role.textContent=r.role;const quote=document.createElement('p');quote.textContent=`“${r.quote}”`;content.append(meta,name,role,quote);const actions=document.createElement('div');actions.className='slide-actions';const edit=document.createElement('button');edit.textContent='Edit';edit.addEventListener('click',()=>editReview(i));const del=document.createElement('button');del.textContent='Delete';del.className='delete';del.addEventListener('click',()=>{if(confirm('Delete this client review?')){data.reviews.splice(i,1);save();renderReviews();toast('Client review removed from the website.')}});actions.append(edit,del);card.append(avatar,content,actions);reviewList.append(card)});document.querySelectorAll('[data-review-count]').forEach(x=>x.textContent=data.reviews.length);document.querySelector('[data-stat-reviews]').textContent=String(data.reviews.length).padStart(2,'0')}
function editReview(i){const r=data.reviews[i];reviewEditor.hidden=false;reviewEditor.elements.index.value=i;['name','role','category','quote','rating'].forEach(k=>reviewEditor.elements[k].value=r[k]);reviewEditor.elements.photo.value=r.photo||'';setReviewPhotoPreview(r.photo||'');document.querySelector('[data-review-editor-title]').textContent='Edit client review';reviewEditor.scrollIntoView({behavior:'smooth',block:'start'})}
document.querySelector('[data-add-review]').addEventListener('click',()=>{reviewEditor.reset();reviewEditor.hidden=false;reviewEditor.elements.index.value='new';setReviewPhotoPreview('');document.querySelector('[data-review-editor-title]').textContent='Add new client review';reviewEditor.scrollIntoView({behavior:'smooth',block:'start'})});document.querySelectorAll('[data-close-review-editor]').forEach(x=>x.addEventListener('click',()=>reviewEditor.hidden=true));
document.querySelector('[data-review-photo-upload]')?.addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1500000){alert('For this browser demo, select an image under 1.5 MB.');e.target.value='';return}const reader=new FileReader();reader.onload=()=>{reviewEditor.elements.photo.value=reader.result;setReviewPhotoPreview(reader.result);toast('Client photo ready — publish to save.')};reader.readAsDataURL(file);e.target.value=''});
document.querySelector('[data-clear-review-photo]')?.addEventListener('click',()=>{reviewEditor.elements.photo.value='';setReviewPhotoPreview('')});
reviewEditor.elements.photo?.addEventListener('input',()=>setReviewPhotoPreview(reviewEditor.elements.photo.value.trim()));
reviewEditor.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(reviewEditor),r={name:f.get('name').trim(),role:f.get('role').trim(),category:f.get('category').trim(),quote:f.get('quote').trim(),rating:Number(f.get('rating')),photo:(f.get('photo')||'').trim()};const i=f.get('index');if(i==='new')data.reviews.push(r);else data.reviews[Number(i)]=r;save();renderReviews();reviewEditor.hidden=true;toast('Client review saved and published locally.')});
let catalogType='services';const catalogList=document.querySelector('[data-catalog-list]'),catalogEditor=document.querySelector('[data-catalog-editor]');
function renderCatalog(){catalogList.innerHTML='';data[catalogType].forEach((item,i)=>{const card=document.createElement('article');card.className='catalog-card';if(item.image){const img=document.createElement('img');img.src=item.image;img.alt='';card.append(img)}const copy=document.createElement('div');copy.innerHTML=`<small>${item.meta}</small><b>${item.name}</b><p>${item.description}</p><span class="publish-state ${item.active?'live':'draft'}">${item.active?'Published':'Hidden'}</span>`;const actions=document.createElement('div');actions.className='slide-actions';const edit=document.createElement('button');edit.textContent='Edit';edit.onclick=()=>editCatalog(i);const toggle=document.createElement('button');toggle.textContent=item.active?'Hide':'Publish';toggle.onclick=()=>{item.active=!item.active;save();renderCatalog();toast()};const del=document.createElement('button');del.textContent='Delete';del.className='delete';del.onclick=()=>{if(confirm(`Delete ${item.name}?`)){data[catalogType].splice(i,1);save();renderCatalog();toast('Catalogue item deleted.')}};actions.append(edit,toggle,del);card.append(copy,actions);catalogList.append(card)});document.querySelectorAll('[data-service-count]').forEach(x=>x.textContent=data.services.length)}
function editCatalog(i){const item=data[catalogType][i];catalogEditor.hidden=false;catalogEditor.elements.index.value=i;catalogEditor.elements.type.value=catalogType;['name','meta','description','image'].forEach(k=>catalogEditor.elements[k].value=item[k]||'');catalogEditor.elements.active.checked=item.active;catalogEditor.querySelector('.catalog-image-field').hidden=catalogType==='areas';document.querySelector('[data-catalog-title]').textContent=`Edit ${catalogType==='areas'?'service area':'service'}`;catalogEditor.scrollIntoView({behavior:'smooth',block:'start'})}
document.querySelectorAll('[data-catalog-tab]').forEach(b=>b.onclick=()=>{catalogType=b.dataset.catalogTab;document.querySelectorAll('[data-catalog-tab]').forEach(x=>x.classList.toggle('active',x===b));renderCatalog();catalogEditor.hidden=true});document.querySelector('[data-add-catalog]').onclick=()=>{catalogEditor.reset();catalogEditor.hidden=false;catalogEditor.elements.index.value='new';catalogEditor.elements.type.value=catalogType;catalogEditor.elements.active.checked=true;catalogEditor.querySelector('.catalog-image-field').hidden=catalogType==='areas';document.querySelector('[data-catalog-title]').textContent=`Add ${catalogType==='areas'?'service area':'service'}`};document.querySelectorAll('[data-close-catalog]').forEach(x=>x.onclick=()=>catalogEditor.hidden=true);
catalogEditor.onsubmit=e=>{e.preventDefault();const f=new FormData(catalogEditor),item={name:f.get('name').trim(),meta:f.get('meta').trim(),description:f.get('description').trim(),image:f.get('image').trim(),active:f.get('active')==='on'},type=f.get('type'),i=f.get('index');if(i==='new')data[type].push(item);else data[type][Number(i)]=item;save();catalogType=type;renderCatalog();catalogEditor.hidden=true;toast('Catalogue updated locally.')};
const statusClass=s=>s.toLowerCase().replace(/\s+/g,'-');
function renderEnquiries(){const list=document.querySelector('[data-enquiry-list]'),q=(document.querySelector('[data-enquiry-search]').value||'').toLowerCase(),filter=document.querySelector('[data-enquiry-filter]').value;list.innerHTML='';data.enquiries.filter(x=>(filter==='All'||x.status===filter)&&`${x.name} ${x.company} ${x.service} ${x.location}`.toLowerCase().includes(q)).forEach((x,i)=>{const card=document.createElement('article');card.className='business-record';card.innerHTML=`<span class="record-id">${x.id}</span><div class="record-primary"><b>${x.name}</b><small>${x.company}</small></div><div><small>Service</small><b>${x.service}</b></div><div><small>Location</small><b>${x.location}</b></div><div><small>Received</small><b>${x.date}</b></div>`;const select=document.createElement('select');['New','Contacted','Quoted','Won','Lost'].forEach(s=>select.add(new Option(s,s)));select.value=x.status;select.className=`record-status ${statusClass(x.status)}`;select.onchange=()=>{x.status=select.value;save();renderEnquiries();toast('Enquiry status updated.')};const actions=document.createElement('div');actions.className='record-actions';actions.innerHTML=`<a href="mailto:${x.email}">Email</a><a href="tel:${x.phone}">Call</a>`;card.append(select,actions);list.append(card)});['New','Contacted','Quoted','Won'].forEach(s=>document.querySelector(`[data-pipeline="${s}"]`).textContent=data.enquiries.filter(x=>x.status===s).length);document.querySelectorAll('[data-enquiry-count]').forEach(x=>x.textContent=data.enquiries.filter(x=>x.status==='New').length)}
document.querySelector('[data-enquiry-search]').oninput=renderEnquiries;document.querySelector('[data-enquiry-filter]').onchange=renderEnquiries;document.querySelector('[data-export-enquiries]').onclick=()=>{const rows=[['ID','Name','Company','Service','Location','Status'],...data.enquiries.map(x=>[x.id,x.name,x.company,x.service,x.location,x.status])],csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='cfs-enquiries.csv';a.click();URL.revokeObjectURL(a.href);toast('Enquiry report exported.')};
function renderApplications(){const list=document.querySelector('[data-application-list]'),q=(document.querySelector('[data-application-search]').value||'').toLowerCase(),filter=document.querySelector('[data-application-filter]').value;list.innerHTML='';data.applications.filter(x=>(filter==='All'||x.status===filter)&&`${x.name} ${x.role}`.toLowerCase().includes(q)).forEach(x=>{const card=document.createElement('article');card.className='business-record application-record';card.innerHTML=`<span class="record-id">${x.id}</span><div class="record-primary"><b>${x.name}</b><small>${x.email}</small></div><div><small>Applied role</small><b>${x.role}</b></div><div><small>Documents</small><b>${x.documents}</b></div><div><small>Submitted</small><b>${x.date}</b></div>`;const select=document.createElement('select');['Pending','Approved','Needs documents','Rejected'].forEach(s=>select.add(new Option(s,s)));select.value=x.status;select.className=`record-status ${statusClass(x.status)}`;select.onchange=()=>{x.status=select.value;save();renderApplications();toast('Application status updated.')};const view=document.createElement('button');view.className='record-view';view.textContent='Review';view.onclick=()=>alert(`${x.name}\n${x.role}\nDocuments received: ${x.documents}\nStatus: ${x.status}\n\nDemo record only — connect the secure backend for real applications.`);card.append(select,view);list.append(card)});document.querySelectorAll('[data-application-count]').forEach(x=>x.textContent=data.applications.filter(x=>x.status==='Pending'||x.status==='Needs documents').length)}
document.querySelector('[data-application-search]').oninput=renderApplications;document.querySelector('[data-application-filter]').onchange=renderApplications;
function renderMedia(){const grid=document.querySelector('[data-media-grid]');grid.innerHTML='';data.media.forEach((m,i)=>{const card=document.createElement('article');const img=document.createElement('img');img.src=m.src;img.alt=m.name;const copy=document.createElement('div');copy.innerHTML=`<small>${m.type}</small><b>${m.name}</b>`;const actions=document.createElement('div');actions.className='media-actions';const use=document.createElement('button');use.textContent='Copy path';use.onclick=async()=>{try{await navigator.clipboard.writeText(m.src);toast('Image path copied.')}catch{prompt('Copy image path:',m.src)}};const del=document.createElement('button');del.textContent='Delete';del.onclick=()=>{if(confirm('Remove this media item?')){data.media.splice(i,1);save();renderMedia()}};actions.append(use,del);card.append(img,copy,actions);grid.append(card)});document.querySelectorAll('[data-media-count]').forEach(x=>x.textContent=data.media.length)}
document.querySelector('[data-media-upload]').onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>1500000){alert('For this browser demo, select an image under 1.5 MB.');return}const reader=new FileReader();reader.onload=()=>{data.media.unshift({name:file.name,src:reader.result,type:'Uploaded image'});save();renderMedia();toast('Image added to the demo media library.')};reader.readAsDataURL(file);e.target.value=''};
const contactForm=document.querySelector('[data-contact-form]');function fillContact(){Object.entries(data.contact).forEach(([k,v])=>{if(contactForm.elements[k])contactForm.elements[k].value=v})}contactForm.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);Object.keys(defaults.contact).forEach(k=>data.contact[k]=f.get(k).trim());save();document.querySelector('[data-contact-status]').textContent='Saved and published locally ✓';toast()});
document.querySelector('[data-reset-site]').addEventListener('click',()=>{if(confirm('Restore all demo content and business records to the original defaults?')){data=clone(defaults);save();renderSlides();renderReviews();renderCatalog();renderEnquiries();renderApplications();renderMedia();fillContact();toast('Original website content restored.')}});
